insert into book (title, author, dateout, loanuser, bookstate) values ('Glass Menagerie, The', 'Tedi', '0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Diabolique (Les diaboliques)', 'Umberto','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('No Way Out', 'Boyd','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Cabiria', 'Gayelord','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Dead Snow 2: Red vs. Dead ', 'Brew','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Amores Perros (Love`s a Bitch)', 'Chester','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Ninth Configuration, The (a.k.a. Twinkle, Twinkle, Killer Kane)', 'Halley''0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Midsummer Night`s Dream, A', 'Karol','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Six in Paris (Paris vu par...)', 'Julee','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('20,000 Leagues Under the Sea', 'Jacky','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Rescuers Down Under, The', 'Annadiana','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Man of the West', 'Cort','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Farewell, Home Sweet Home (Adieu, plancher des vaches!)', 'Daphne','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Daffy Duck''s Movie: Fantastic Island', 'Cheryl','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('War on Democracy, The', 'Claudelle','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Going the Distance', 'Egan','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Barchester Chronicles, The', 'Tommie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Izo', 'Patsy','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Last Wave, The', 'Kellen','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Chico & Rita', 'Hanson','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Dogs in Space', 'Luisa','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Shinobi No Mono 2: Vengeance (Zoku shinobi no mono)', 'Batsheva','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Chain Letter', 'Tami','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Dracula (Dracula 3D)', 'Yetty','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('The Woman in Black 2: Angel of Death', 'Terrijo','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Choppertown: The Sinners', 'Willie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Elvira, Mistress of the Dark', 'Rossy','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Pillars of the Earth, The', 'Kyle','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('G', 'Adeline','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('We Steal Secrets: The Story of WikiLeaks', 'Ira','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Cry-Baby', 'Pandora','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Take the Lead', 'Wynne','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('I as in Icarus (I... comme Icare)', 'Guntar','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Starship Troopers 3: Marauder', 'Lorine','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('We and the I, The', 'Dolores','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('It''s Such a Beautiful Day', 'Lyndsie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('We Cause Scenes', 'Brant','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Cain and Mabel', 'Erena','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('We Can Be Heroes', 'Tamas','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Girl Play', 'Ingeborg','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('The Passerby', 'Nelie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Absolute Giganten', 'Rourke','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('January Man, The', 'Veronike','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Son, The (Le fils)', 'Malva','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Unborn in the USA: Inside the War on Abortion', 'Koenraad','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Homem Que Desafiou o Diabo, O', 'Harriott','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Cowboy Bebop', 'Lelah','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('One Hour Photo', 'Rebbecca','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('The Devil and the Holy Water', 'Marcille','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('X-Files: I Want to Believe, The', 'Andi','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Big Brown Eyes', 'Orion','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('The Trip to Bountiful', 'Ulrike','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Time to Love and a Time to Die, A', 'Brod','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Too Many Girls', 'Sonnie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Seven Psychopaths', 'Marlo','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Bonsái', 'Ulrich','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Blood and Wine (Blood & Wine)', 'Barbey','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Goldfish Memory', 'Tucky','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('High School Musical', 'Phyllys','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('I Was Monty`s Double', 'Olwen','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Hamlet', 'Stormy','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Casa de los babys', 'Ursulina','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Mysteries of Pittsburgh, The', 'Brittney','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Puppet Master: Axis of Evil (Puppet Master 10)', 'Bay','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Holiday Affair', 'Camellia','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Above Suspicion', 'Harwilll','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Story of Floating Weeds, A (Ukikusa monogatari)', 'Dominik','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Princesas', 'Margy','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Kanak Attack', 'Shirleen','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Masque of the Red Death, The', 'Jessee','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('TerrorStorm: A History of Government-Sponsored Terrorism', 'Curcio','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Sovereign''s Company', 'Nicoli','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Verboten!', 'Maible','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Moscow Does Not Believe in Tears (Moskva slezam ne verit)', 'Thorn','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Wild Child, The (Enfant sauvage, L'')', 'Hamlin','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Gorilla, The', 'Deny','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Wishful Thinking', 'Jorry','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Going Clear: Scientology and the Prison of Belief', 'Turner','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Mike Tyson:  Undisputed Truth', 'Evered','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Holiday (Jour de fête)', 'Stanly','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('North and South, Book I', 'Stu','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Phantom, The', 'Suzie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Inside Man', 'Dorena','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Go for Zucker! (Alles auf Zucker!)', 'Millard','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('The Russian Novel', 'Ashely','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Papadopoulos & Sons', 'Othilie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Smiling Lieutenant, The', 'Meridith','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Ready to Rumble', 'Sandra','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Human Planet', 'Tally','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('How to Succeed in Business Without Really Trying', 'Lorrie','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('War, Inc.', 'Ramsay','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Atlas Shrugged: Part II', 'Barby','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Kingsman: The Secret Service', 'Analise','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('La Première étoile', 'Dunstan','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Young Girls of Rochefort, The (Demoiselles de Rochefort, Les)', 'Horacio','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Trash', 'Perri','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Aftershock', 'Nikki','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Girl Can''t Help It, The', 'Sybille','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Substance of Fire, The', 'Garrek','0001-01-01', 'admin', 'available');
insert into book (title, author, dateout, loanuser, bookstate) values ('Boogie Woogie', 'Margalo','0001-01-01', 'admin', 'available');
